package es.unizar.webeng.hello.entity 

import es.unizar.webeng.hello.enum.Endpoint
import es.unizar.webeng.hello.enum.TimeOfDay
import es.unizar.webeng.hello.enum.timestampToTimeOfDay
import jakarta.persistence.*
import java.time.OffsetDateTime


/**
 * Represents a greeting sent by a user.
 *
 * @property endpoint The type of [Endpoint] through which the greeting was sent.
 * @property user The user who sent the greeting.
 * @property name The name included in the greeting message.
 * @property timestamp The date and time when the greeting was created. Defaults to the current time.
 * @property id Unique identifier for the greeting. Auto-generated by the database.
 */
@Entity
@Table(name = "GREETINGS")
class Greeting(
    @Enumerated(EnumType.STRING)
    val endpoint: Endpoint,

    @ManyToOne
    @JoinColumn(name = "user_id")
    val user: User,

    val name: String,

    val timestamp: OffsetDateTime = OffsetDateTime.now(),

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0  
) {
    
    /**
     * Returns the [TimeOfDay] corresponding to the greeting's timestamp.
     *
     * Calculated using [timestampToTimeOfDay].
     */
    val timeOfDay: TimeOfDay
        get() = timestampToTimeOfDay(timestamp)
}
