package es.unizar.webeng.hello.entity

import es.unizar.webeng.hello.enum.Role
import jakarta.persistence.*
import java.util.UUID


/**
 * Represents a user of the application.
 *
 * @property username The unique username of the user.
 * @property password The password for authentication.
 * @property role The [Role] assigned to the user. 
 * @property greetings The list of [Greeting]s created by this user.
 *   Orphan removal and cascade delete ensure that greetings are removed if the user is deleted.
 * @property id Unique identifier for the user. Auto-generated by the database.
 */
@Entity
@Table(name = "USERS")
class User(
    @Column(unique = true, nullable = false)
    val username: String = "",

    @Column(nullable = false)
    val password: String = "",

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    val role: Role = Role.USER,

    @OneToMany(mappedBy = "user", cascade = [CascadeType.REMOVE], orphanRemoval = true)
    val greetings: MutableList<Greeting> = mutableListOf(),
    
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0
)
